### ISSUE TITLE
Linux baseline: Ensure mail transfer agent is configured for local-only mode error

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec-policies#87]
**Describe the bug**
When scanning a Fedora 36 container image the Linux baseline security policy's `Ensure mail transfer agent is configured for local-only mode` control throws this error:

```
[
  {
    "error": "cannot convert primitive with NO type information"
  },
  {
    "error": "cannot convert primitive with NO type information"
  },
  null
]
```

**To Reproduce**
1. cnspec scan docker image dokken/fedora-36

**Comment by chris-rock** [comment]
Seems like this error is not reproducible with latest cnquery / cnspec. It highlighted another issue with the error message though, which was unspecific on container images. This fix is up here https://github.com/mondoohq/cnquery/pull/741

I also think we should change https://github.com/mondoohq/cnspec-policies/blob/main/core/mondoo-linux-security.mql.yaml#L673-L680 to use the `ports` resource since it is more flexible and as various fallbacks for different environments.
